name: build-sphinx-to-gh-pages
on:
  push:
    branches:
    - master

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-serial-dev libopenmpi-dev openmpi-bin libgsl-dev

      - uses: actions/checkout@v4
      - name: Install pip requirements
        run: |
          pip install -e .
          pip install -e .[docs]
      - name: Sphinx build
        run: |
          git checkout -b gh-pages
          mkdir docs
          sphinx-build -b html doc/ docs
          touch docs/.nojekyll
      - name: Commit site
        run: |
          git config --global user.name 'Rick Nitsche (automated)'
          git config --global user.email 'nritsche@users.noreply.github.com'
          git add .
          git commit -am "Automated sphinx build"
          git push --force origin gh-pages
